# Investigación sobre el algoritmo Minimax y Alpha-Beta prunning

### Historia

Alan Turing en 1937 publicó un artículo en el cual describe una máquina o calculadora denominada Máquina de Turing, la cual funciona basándose en una serie de instrucciones lógicas, esto fue la base del concepto de algoritmo.

Durante la historia son muchas personas que aportaron al avanze de la ingenieria y la tecnologia de los sitemas computacionales. En el a~no 1950 cuando fue posible porgramar computadoras los inventores Claude Shannon el cual invento la teoría de la información, y Alan Turing realizaron los primeros programas de IA los cuales podian jugar ajedrez. 

Alan Turing fuen de los primeros en desarrollar un programa de ordenador para el juego de ajedrez, luego de desarrollar el programa escribio un articulo denominado Digital Computers Applied to games. La publicacion de este articulo tubo gran exito para el desarrollo de futuros programas y juegos.

### Algoritmo Minimax

Este algoritmos utiliza una busqueda en profundidad limitada. Este algoritmo emplea una funcion estatica la cual devuelve valores en funcion del jugador maximo, este algortmo trata de maximizar el valor de los jugadores mientras que un oponente trata de minimizarlo. 


Dentro de la teoria de juegos este algoritmo sirve para minimizar la perdida que se puede esperar en un juego contra un adversario donde se tiene informacion necesaria para determinar esto. Este algoritmo permite determinar o elegir un movimiento en un escenario donde mi contrincate escoge lo peor. 

Pasos del algoritmo Minimax: 

1. Se Genera un arbol de juego, se genera los nodos hasta un estado final.
2. Calcula una funcion de utilidad para cada nodo fina.
3. Calcula el valor de los nodos superiores en base a los nodos inferiores. Para elegir los movimiento del jugador y oponente se eligen valores maximos y minimos representanto movimientos.
4. Realiza un movimiento en base al valor superio que tiene el nodo en el arbol de juego.
 
Para la optimizacion de la busqueda en el arborl Claude propuso que se utilizaran otras funciones heuristicas como la busqueda por profundidad o por tiempo de ejecucion. Este algoritmo garantiza encontrar un moviento asuminedo que el jugador siempre realiza los movimientos de manera optima, este algortmo dependera de su optimo desarrollo en base a la profundidad del arbol de juego generado. 

Una de las principales caracteristicas es de crear escenarios complicados empleando reglas sencillas. Los juegos con estos algoritmos pueden ser testeados con jugadores contra maquinas. Este algoritmo al ser recursivo su terminacion o corte esta condicionada, estas condiciones pueden ser:

    -Gana un jugador
    -Se ha explorado el arbol y no hay mas capas
    -Se ha exedido el tiempo
    -Se ha llegado a un nivel sin cambios.


### Alpha-Beta prunning

Alpha-Bta prunning es denominado una tecnica que sirve para reducir el numero de nodos que se tiene que evaluar por el algoritmo minimax. Este tipo de tecnica reliza un tipo de corte o poda del arbol de busqueda y los nodos que representan los movinenotos tales que permiten que al jugador el controncante no le supere.

Esta tecnica fue analizada por Donald Knuth y Ronald Moore en 1975 en donde prponian la eficiencia de esta tecnica que decia que es posible encontrar una decision o nodo correcto sin recorrer todo el arbol de buqueda. Esta tecnica produce un movimiento, o jugada similar al algoritmo minimax, sin embargo esta tecnica reduce el recorrido del arbol de busqueda y su eficiencia deoendera de como se vaya explorando el arbol y de sus nodos sucesores. 

Este metodo realiza un mejor rendimiento en cuanto al algortimo minimax en cuanto al tiempo empleodo para el calculo de un movimiento donde se explora las ramas mas favorables y se quita o no explora aquellas que tienen probabilidad de realizar una jugada errada.

La tecnica de ALpha-Beta prunning es muy aplicable en espacios grandes donde se requiere un rendiemiento y eficiencia, para ello se tiene que explorar aquelllas partes de arbol con mayor porbabilidad de exito. Dentro de esto tenemos 2 caracteristicas que son:

    -ALfa: Representa el valor maximo que se tiene en periodo o punto de eleccion a traves de la ruta de busqueda.
    -Beta: Esto representa el valor minimo o mas bajo encontrada en ese momento o punto a lo largo de la ruta de busqueda.

Estos valores de alfa y beta se van actualizando conforme se va avanzado la busqueda y se va realizando la poda de aquellas ramas del arbol que no representan un exito. Esto se realiza con un arbol y una busqueda heuristica con profundidad limitada para poder podar o itnerrunpir las busquedas en nodos no favorables. Este corte o poda no afecta al resultado final ya que se consigue el mismo resultado sin aplicar esta tecnica al algoritmo minimax.


### Ejemplo

Uno de los juegos que implementa este algoritmo es el juego de 3 en raya, el cual implementaa el minimax para determinar las jugadas o movimientos que pueden realizarse. En el siguiente link se puede encontrar el juego desarrollado implementado el algoritmo de minimax.

Este algoritmo es el siguiente: 
https://github.com/Cledersonbc/tic-tac-toe-minimax/blob/master/py_version/minimax.py

def minimax(state, depth, player):

    if player == COMP:
        best = [-1, -1, -infinity]
    else:
        best = [-1, -1, +infinity]

    if depth == 0 or game_over(state):
        score = evaluate(state)
        return [-1, -1, score]

    for cell in empty_cells(state):
        x, y = cell[0], cell[1]
        state[x][y] = player
        score = minimax(state, depth - 1, -player)
        state[x][y] = 0
        score[0], score[1] = x, y

        if player == COMP:
            if score[2] > best[2]:
                best = score  # max value
        else:
            if score[2] < best[2]:
                best = score  # min value

    return best


### Aplicaciones Practicas

EL algoritmo de minimax y alpha-Beta prunning son muy utilizados en el desarrollo de juegos. Algunos de los juegos desarrollados son el juego mancala el cual es un juego de tablero para 2 jugadores. Este juego es utilizado para emplear el algoritmo ya que cuenta con 64 fichas y 32 huecos que con la logica del juego se pueden emplear diversos movimientos. 

Otro juego en el cual es empleado el algoritmo minimax con alpha-beta es el juego tres en raya. Este juego implementa este algorimo para poder dar y tenenr los movieminetos acertados implementando la tecnica alpha-beta que permite optimizar este algoritmo para poder tener resultados efectivos sin tener que recorrer todo el arbol de movimientos o jugas. 

EL centro de investigacions en computacion del Instituto Politecnico Nacional de Mexico realizo una investigacion sobre el reconocimineto de de voz emotiva con memoria asociativa implementando Alpha-Beta. 

#### Referencias:

Gerardo, L. (2012). Alan Turing y Ajedrez . Cinvestav: Departamento de Computación.
Alvarado, J. (2005). Minimax. Nuevo Laredo: Instituto Tecnologico Nuevo Loredo.

Solís Villarreal, J., Yáñez Márquez, C., & Suárez Guerra, S. (2020). Reconocimiento automático de voz emotiva con memorias asociativas Alfa-Beta SVM. Retrieved 15 July 2020, from http://www.scielo.org.mx/scielo.php?pid=S1870-90442011000200004&script=sci_arttext&tlng=en

Algoritmo Minimax aplicado a vigilancia con robots móviles. (2020). Retrieved 15 July 2020, from https://grvc.us.es/staff/svera/doc/minimax.pdf

Ruiz, L., Motsarenkoose, A., & Leon, A. (2020). JUEGO MANCALA CON ALGORITMO MINIMAX REALIZADO CON INTERFAZ GRÁFICA EN JAVA [Ebook]. Retrieved from http://www.it.uc3m.es/~jvillena/irc/practicas/12-13/05mem.pdf


Santos, S., García, G., García, R., Gómez, I., & Anwar, G. (2020). Inteligencia Artificial. Retrieved 15 July 2020, from http://www.itnuevolaredo.edu.mx/takeyas/Apuntes/Inteligencia%20Artificial/Apuntes/tareas_alumnos/Alfa-Beta/Alfa-Beta(2005-II-A).pdf?fbclid=IwAR1NwmVKTaJ8n4d3J8LFAxzIueEWK5Hqgtn03Sw1q5_fsbL3Q1o_7e5oomo


####  Desarrollo de Juego

In [2]:
from easyAI import TwoPlayersGame, Human_Player, AI_Player, Negamax
import numpy as np

In [5]:
class juegoFichas(TwoPlayersGame):

    def __init__(self, nplayers):
        self.n = int(input("Ingrese el numero de fichas con las que va a jugar: \n"))
        print(self.n)
        self.fichas = np.zeros(self.n, dtype=int)
        self.nplayer = 1
        self.players = nplayers
        print(self.fichas)
        print(self.players)
        
    def possible_moves(self):

        moves = []
        cont = 1        
        for i in range(len(self.fichas)):
            if self.fichas[i] == 0:
                moves.append(cont)
            cont += 1
        print(moves)        
        return moves

    def make_move(self, casillero):
        self.fichas=np.delete(self.fichas,casillero-1)
        #print(self.fichas)
    def lose(self):
        if self.fichas.size==0:
            return True
        return False
    def show(self):
        print(self.fichas)

    def scoring(self):
        return -100 if self.lose() else 0
    def is_over(self):

        if (self.fichas.size==0):
            print("Juego terminado, gano el jugador: ", self.nplayer)

        return (self.possible_moves()==0 or self.lose())



if __name__ == "__main__":
    maquina = Negamax(3)
    juego = juegoFichas([Human_Player(), AI_Player(maquina)])
    juego.play()

Ingrese el numero de fichas con las que va a jugar: 
5
5
[0 0 0 0 0]
[<easyAI.Player.Human_Player object at 0x7f3e9dca3d10>, <easyAI.Player.AI_Player object at 0x7f3e9dca57d0>]
[0 0 0 0 0]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]

Player 1 what do you play ? 4

Move #1: player 1 plays 4 :
[0 0 0 0]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3]
[1, 2, 3]
[1, 2]
[1, 2]
[1, 2]
[1, 2]
[1, 2]
[1, 2]
[1, 2, 3]
[1, 2, 3]
[1, 2]
[1, 2]
[1, 2, 3]
[1, 2, 3]
[1, 2]
[1, 2]
[1, 2, 3]
[1, 2, 3]
[1, 2]
[1, 2]

Move #2: player 2 plays 1 :
[0 0 0]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]

Player 1 what do you play ? 3

Move #3: player 1 plays 3 :
[0 0]
[1, 2]
[1, 2]
[1, 2]
[1]
[1]
Juego terminado, gano el jugador:  2
[]
[1]
[1]
Juego terminado, gano el jugador:  2
[]

Move #4: player 2 plays 1 :
[0]
[1]
[1]
[1]

Player 1 what do you play ? 1

Move #5: player 1 plays 1 :
[]
Juego terminado, gano el jugador:  2
[]
